name: Unix Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install clang-format
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 11
          rm llvm.sh
          sudo apt-get install -y --no-install-recommends clang-format-11

      - name: Format files
        run: find src include test exe -type f -a \( -name "*.cc" -o -name "*.h" \) -print0 | xargs -0 clang-format-11 -i

      - name: Check for differences
        run: |
          git status --porcelain
          git status --porcelain | xargs -I {} -0 test -z \"{}\"

  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: MacOS Release
            cxx: clang++
            cc: clang
            mode: Release
            cxxflags: -stdlib=libc++
            os: macos-latest
            artifact: macos
          - name: GCC 10 Release
            cxx: g++-10
            cc: gcc-10
            mode: Release
            os: ubuntu-20.04
            artifact: linux
          - name: GCC 10 Debug
            cxx: g++-10
            cc: gcc-10
            mode: Debug
            os: ubuntu-20.04
          - name: Clang 11 Release
            cxx: clang++-11
            cc: clang-11
            mode: Release
            cxxflags: -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-20.04
          - key: Clang 11 Sanitizer
            cxx: clang++-11
            cc: clang-11
            mode: Release
            cflags: -fsanitize=address,undefined -fno-omit-frame-pointer
            cxxflags: -fsanitize=address,undefined -fno-omit-frame-pointer -stdlib=libc++
            ldflags: -lc++abi
            os: ubuntu-20.04
    env:
      UBSAN_OPTIONS: halt_on_error=1:abort_on_error=1
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      # ==== INSTALL ====
      - name: Upgrade Packages
        if: matrix.config.os != 'macos-latest'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update

      - name: Install LLVM
        if: matrix.config.os != 'macos-latest' && matrix.config.cc == 'clang-11'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 11
          rm llvm.sh
          sudo apt-get install -y --no-install-recommends libc++-11-dev libc++abi-11-dev clang-tidy-11

      - name: Install Valgrind
        if: matrix.config.mode == 'Debug' && matrix.config.cc == 'gcc-10'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -y --no-install-recommends valgrind

      # ==== CACHING ====
      - name: buildcache Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ github.workspace }}/.buildcache
          key: buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-${{ hashFiles('**/*.cc') }}
          restore-keys: |
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-${{ hashFiles('.pkg') }}-
            buildcache-${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.mode }}-${{ contains(matrix.config.cxxflags, 'sanitize') }}-${{ matrix.config.lint }}-

      - name: Dependencies Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ github.workspace }}/deps
          key: deps-${{ hashFiles('.pkg') }}
          restore-keys: deps-

      # ==== BUILD ====
      - name: CMake
        run: |
          cmake \
          -G Ninja -S . -B build \
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
          -DCMAKE_C_FLAGS="${{ matrix.config.cflags }}" \
          -DCMAKE_CXX_FLAGS="${{ matrix.config.cxxflags }}" \
          -DCMAKE_CXX_FLAGS_DEBUG="" \
          -DCMAKE_CXX_LINKER_FLAGS=${{ matrix.config.ldflags }}" \
          -DCMAKE_CXX_EXE_LINKER_FLAGS="${{ matrix.config.ldflags }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }}

      - name: Build
        run: |
          ./build/bin/buildcache -z
          cmake --build build --target botscript-server-tests botscript-server-exe c_bss
          ./build/bin/buildcache -s

      # ==== TESTS ====
      - name: Run Tests
        run: ./build/botscript-server-tests

      # ==== VALGRIND ====
      - name: Run Tests Valgrind
        if: matrix.config.mode == 'Debug' && matrix.config.cc == 'gcc-10'
        run: valgrind --error-exitcode=1 --show-reachable=yes --leak-check=full ./build/botscript-server-tests

      # ==== PACKAGING ====
      - name: Package Linux
        if: matrix.config.mode == 'Release' && matrix.config.cc == 'gcc-10'
        run: |
          VERSION=`git describe --tags --dirty=-dirty --always`
          RELEASE_DIR=makielskisbot-server-${VERSION}
          mkdir ${RELEASE_DIR}
          strip build/botscript-server-exe
          cp build/botscript-server-exe ${RELEASE_DIR}/makielskisbot
          zip -9 -r makielskisbot-${{ matrix.config.artifact }}.zip ${RELEASE_DIR}

      - name: Package Mac OS
        if: matrix.config.os == 'macos-latest'
        run: |
          VERSION=`git describe --tags --dirty=-dirty --always`
          strip build/libc_bss.dylib
          cp build/libc_bss.dylib mac_res/makielskisbot-mac.app/Contents
          zip -9 -r makielskisbot-${{ matrix.config.artifact }}.zip mac_res/makielskisbot-mac.app

      # ==== DISTRIBUTION ====
      - name: Upload Distribution
        if: matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-10' || matrix.config.os == 'macos-latest')
        uses: actions/upload-artifact@v1
        with:
          name: makielskisbot-${{ matrix.config.artifact }}
          path: makielskisbot-${{ matrix.config.artifact }}.zip

      # ==== RELEASE ====
      - name: Upload Release
        if: github.event.action == 'published' && matrix.config.mode == 'Release' && (matrix.config.cc == 'gcc-10' || matrix.config.os == 'macos-latest')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: makielskisbot-${{ matrix.config.artifact }}.zip
          asset_name: makielskisbot-${{ matrix.config.artifact }}.zip
          asset_content_type: application/zip